/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.User;
import model.UserList;

/**
 *
 * @author sanatpopli
 */
public class CreateAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateAccountJPanel
     */
  

    /**
     * Creates new form CreateAccountJPanel
     */
    
    private JPanel userProcessContainer;
    private UserList userlist;
    
    CreateAccountJPanel(JPanel userProcessContainer, UserList userlist) {
        initComponents();
        
        this.userProcessContainer=userProcessContainer;
        this.userlist=userlist;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerjLabel = new javax.swing.JLabel();
        accountnumjlabel = new javax.swing.JLabel();
        useridjLabel = new javax.swing.JLabel();
        usernamejLabel = new javax.swing.JLabel();
        passwordjLabel = new javax.swing.JLabel();
        createaccjButton = new javax.swing.JButton();
        txtNeuid = new javax.swing.JTextField();
        txtUserid = new javax.swing.JTextField();
        txtUserName = new javax.swing.JTextField();
        backjButton = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        CheckBoxSelect = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(255, 204, 153));

        headerjLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        headerjLabel.setText("Create Account");

        accountnumjlabel.setText("Account");

        useridjLabel.setText("User ID");

        usernamejLabel.setText("Name");

        passwordjLabel.setText("Password");

        createaccjButton.setText("Create");
        createaccjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createaccjButtonActionPerformed(evt);
            }
        });

        backjButton.setText("<<Back");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });

        CheckBoxSelect.setText("Show Password");
        CheckBoxSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxSelectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backjButton)
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createaccjButton)
                            .addComponent(headerjLabel)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(useridjLabel)
                            .addComponent(accountnumjlabel)
                            .addComponent(usernamejLabel)
                            .addComponent(passwordjLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CheckBoxSelect)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                .addComponent(txtNeuid)
                                .addComponent(txtUserid)
                                .addComponent(txtPassword)))))
                .addGap(325, 325, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(headerjLabel)
                    .addComponent(backjButton))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(accountnumjlabel)
                            .addComponent(txtNeuid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtUserid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(useridjLabel))
                        .addGap(38, 38, 38)
                        .addComponent(usernamejLabel))
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(passwordjLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CheckBoxSelect)
                .addGap(25, 25, 25)
                .addComponent(createaccjButton)
                .addContainerGap(173, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createaccjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createaccjButtonActionPerformed
        // TODO add your handling code here:
        
        
        
        Boolean flag = true;
        
        String NEUID = txtNeuid.getText();
            if(NEUID.matches("[0-9]{9}") == false){
                JOptionPane.showMessageDialog(null, "Enter 9 Digit NEU ID");
                flag = false;   
            }
            
        String userid = txtUserid.getText();
            if(userid.matches("[0-9]{9}") == false){
                JOptionPane.showMessageDialog(null, "Enter valid User ID");
                flag = false;   
            }
            
            String password = txtPassword.getText();
            if(password.matches("[a-zA-Z0-9@._-]{3,}") == false){
                JOptionPane.showMessageDialog(null, "Incorrect Password");
                flag = false;   
            }
            
            
            
         
        if(flag == true){
            User user = new User();{
        String neuid=txtNeuid.getText();
        String userId=txtUserid.getText();
        String username=txtUserName.getText();
        String Password=txtPassword.getText();
        
        
        user.setNeuid(neuid);
        user.setUserid(userId);
        user.setUsername(username);
        user.setPassword(Password);
        
        JOptionPane.showMessageDialog(this, "Account created successfully");
    }//GEN-LAST:event_createaccjButtonActionPerformed
        }}
    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout= (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButtonActionPerformed

    private void CheckBoxSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxSelectActionPerformed
        // TODO add your handling code here:
        if(CheckBoxSelect.isSelected()){
            txtPassword.setEchoChar((char)0);
        }
        else{
            txtPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_CheckBoxSelectActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBoxSelect;
    private javax.swing.JLabel accountnumjlabel;
    private javax.swing.JButton backjButton;
    private javax.swing.JButton createaccjButton;
    private javax.swing.JLabel headerjLabel;
    private javax.swing.JLabel passwordjLabel;
    private javax.swing.JTextField txtNeuid;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JTextField txtUserid;
    private javax.swing.JLabel useridjLabel;
    private javax.swing.JLabel usernamejLabel;
    // End of variables declaration//GEN-END:variables
}
